Add list and character component
buentellopc/chapter1-spa pull request #1
Opened 2023-04-11 03:26 UTC by buentellopc

We will retrieve the data in order to fulfill the List and Character components.

Using the following API: https://rickandmortyapi.com/documentation/#rest

2023-04-11 03:33 UTC, frxncismor commented on src/components/List.js
> +    <Character />
We don't need this third character line, can you please delete it?
```suggestion
  
```

2023-04-13 06:32 UTC, buentellopc commented on src/App.js
> +import ParentSearch from "./components/ParentSearch";
```suggestion

```

2023-04-13 06:34 UTC, frxncismor requested changes

2023-04-13 06:34 UTC, frxncismor commented on src/components/Character.css
> +  /* border: 1px solid red; */
Please delete the code you aren't using anymore in order to keep code clean
```suggestion
  
```

2023-04-14 20:23 UTC, frxncismor commented on src/App.js
> +      {/* <InfiniteScroll /> */}
```suggestion

```

2023-04-16 19:26 UTC, frxncismor approved these changes

2023-04-16 19:27 UTC, merged